NEXT_PUBLIC_WEBAPP_URL : http://localhost:3000
NEXTAUTH_SECRET : auth_secret
CALENDSO_ENCRYPTION_KEY : encyrption_secret
NEXT_PUBLIC_LICENSE_CONSENT: NEXT_PUBLIC_LICENSE_CONSENT_PLACEHOLDER 
CALCOM_TELEMETRY_DISABLED : CALCOM_TELEMETRY_DISABLED_PLACEHOLDER 
