version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - calcom_network

  api:
    build:
      context: ../../../
      dockerfile: apps/api/v2/Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:@postgres:5432/calendso
        DATABASE_DIRECT_URL: postgresql://postgres:@postgres:5432/calendso
        API_PORT: 80
    depends_on:
      - redis
      - postgres
    ports:
      - "80:80"
    networks:
      - calcom_network

volumes:
  redis_data:

networks:
  calcom_network:
    external: true
