version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - "5450:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "cal-saml"
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_is_ready:
    image: postgres
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  api:
    build:
      context: ../../../
      dockerfile: apps/api/v2/Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:@postgres:5432/calendso
        DATABASE_DIRECT_URL: postgresql://postgres:@postgres:5432/calendso
        API_PORT: 80
    depends_on:
      - redis
      - postgres
    ports:
      - "80:80"

volumes:
  redis_data: