name: Cache playwright binaries
description: "Cache playwright or restore if necessary"
runs:
  using: "composite"
  steps:
    - name: Cache playwright binaries
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          ${{ github.workspace }}/node_modules/playwright
        key: cache-playwright-${{ hashFiles('**/yarn.lock') }}
        restore-keys: cache-playwright-
