# Starts mailhog SMTP server on port 1025, web interface on port 8025
version: "3.6"
services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
