color: true
dry-run: null
hookfiles: ./dredd-hooks.js
require: null
server-wait: 30
init: false
custom: {}
#  Be warned that no tests will run if this is true.
# names: true
#  Useful for iterating quickly on one test
# only: ["/webhooks > Creates a new webhook > 201", "/webhooks/{id} > Edit an existing webhook > 200"]
reporter: ["html"]
output: ["dredd-output.html"]
sorted: false
user: null
inline-errors: true
details: true
loglevel: error
path: []
hooks-worker-timeout: 50000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: "http://localhost:3002/openapi.yaml"
endpoint: "http://localhost:3002"
