on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  e2e-main:
    name: E2E tests
    needs: [changes, lint, build]
    uses: ./.github/workflows/e2e-main.yml
    secrets: inherit

  e2e-app-store:
    name: E2E App Store tests
    needs: [changes, lint, build]
    uses: ./.github/workflows/e2e-app-store.yml
    secrets: inherit

  e2e-embed:
    name: E2E embeds tests
    needs: [changes, lint, build]
    uses: ./.github/workflows/e2e-embed.yml
    secrets: inherit

  e2e-embed-react:
    name: E2E React embeds tests
    needs: [changes, lint, build]
    uses: ./.github/workflows/e2e-embed-react.yml
    secrets: inherit
