name: PR Update

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Yarn install & cache
    uses: ./.github/workflows/yarn-install.yml

  type-check:
    name: Type check
    needs: setup
    uses: ./.github/workflows/check-types.yml

  lint:
    name: Linters
    needs: setup
    uses: ./.github/workflows/lint.yml

  build:
    name: Production build
    needs: setup
    uses: ./.github/workflows/production-build.yml

  e2e-test:
    name: E2E tests
    needs: [lint, build]
    uses: ./.github/workflows/e2e.yml

  analyze:
    needs: build
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
