name: PR Update

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  node_version: ${{ secrets.NODE_VERSION }}
  pr_id: ${{ github.event.number }}
  # last_commit_sha: ${{ github.event.pull_request.head.sha }}
  gh_action_name: pull_request
  merge_base_cmd: git merge-base origin/${{ github.base_ref }} ${{ github.event.pull_request.head.sha }}

concurrency:
  group: pr-update-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  setup:
    name: Yarn install & cache
    uses: ./.github/workflows/yarn-install.yml
    secrets:
      node_version: ${{ secrets.NODE_VERSION }}
  lint:
    name: Linters
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
          cache_fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_fingerprint }}
      - name: lint the code
        run: yarn lint
  build:
    name: Production build
    needs: setup
    uses: ./.github/workflows/production-build.yml
    secrets:
      node_version: ${{ env.node_version }}

  e2e-test:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: [lint, build]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
          cache_fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_fingerprint }}
        # figure the better way supporting all the packages
      - name: Fake yarn postinstall
        run: yarn playwright install
      - name: Run tests
        run: yarn test-e2e

  bundle-size-report:
    name: Bundle size report

    runs-on: ubuntu-latest

    needs: [build]

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - run: git fetch --no-tags --prune --depth=20 origin main

      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
          cache_fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_fingerprint }}

      - name: Restore exact production build from cache
        uses: actions/cache@v3
        env:
          cache_name: prod-build
          key_1: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
          key_2: ${{ hashFiles('gatsby.config.ts','gatsby.node.ts','gatsby-ssr.tsx','src/html.tsx','src/gatsby-hooks/*.*') }}
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.key_1 }}-${{ env.key_2 }}-${{ github.sha }}

      - name: Find the "merge-base" between target branch and last PR commit
        run: echo "merge_base_sha=$(${{ env.merge_base_cmd }})" >> $GITHUB_ENV
