name: PR Update

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/CODEOWNERS"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      pull-requests: read
    outputs:
      app-store: ${{ steps.filter.outputs.app-store }}
      embed: ${{ steps.filter.outputs.embed }}
      embed-react: ${{ steps.filter.outputs.embed-react }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dangerous Git Checkout
        uses: ./.github/actions/dangerous-git-checkout

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            app-store:
              - 'apps/web/**'
              - 'packages/app-store/**'
            embed:
              - 'apps/web/**'
              - 'packages/embeds/**'
            embed-react:
              - 'apps/web/**'
              - 'packages/embeds/**'

  env:
    name: Create env file
    uses: ./.github/workflows/env-create-file.yml
    secrets: inherit

  type-check:
    name: Type check
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  test:
    name: Unit tests
    uses: ./.github/workflows/test.yml
    secrets: inherit

  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Production build
    needs: env
    uses: ./.github/workflows/production-build.yml
    secrets: inherit

  build-without-database:
    name: Production build (without database)
    needs: env
    uses: ./.github/workflows/production-build-without-database.yml
    secrets: inherit

  e2e:
    name: E2E tests
    needs: [changes, lint, build]
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn run test:e2e

      - name: Verify Embed methods
        run: yarn run verify-embed-methods

  e2e-app-store:
    name: E2E App Store tests
    if: ${{ needs.changes.outputs.app-store == 'true' }}
    needs: [changes, lint, build]
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn run test:e2e-app-store

  e2e-embed:
    name: E2E embeds tests
    if: ${{ needs.changes.outputs.embed == 'true' }}
    needs: [changes, lint, build]
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn run test:e2e-embed

  e2e-embed-react:
    name: E2E React embeds tests
    if: ${{ needs.changes.outputs.embed-react == 'true' }}
    needs: [changes, lint, build]
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn run test:e2e-embed-react

  analyze:
    needs: build
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
    secrets: inherit

  required:
    needs: [lint, type-check, test, build, e2e]
    if: always()
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
