name: PR Update

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/CODEOWNERS"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      app-store: ${{ steps.filter.outputs.app-store }}
      embed: ${{ steps.filter.outputs.embed }}
      embed-react: ${{ steps.filter.outputs.embed-react }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app-store:
              - 'apps/web/**'
              - 'packages/app-store/**'
            embed:
              - 'apps/web/**'
              - 'packages/embeds/**'
            embed-react:
              - 'apps/web/**'
              - 'packages/embeds/**'

  env:
    name: Create env file
    uses: ./.github/workflows/env-create-file.yml
    secrets: inherit

  e2e:
    name: E2E tests
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  required:
    needs: [e2e]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
