name: PR Update

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/CODEOWNERS"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DATABASE_URL: postgresql://postgres:@localhost:5432/calendso
  NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000
  NEXT_PUBLIC_WEBSITE_URL: http://localhost:3000
  NEXTAUTH_SECRET: secret
  GOOGLE_API_CREDENTIALS: ${{ secrets.CI_GOOGLE_API_CREDENTIALS }}
  GOOGLE_LOGIN_ENABLED: true
  # CRON_API_KEY: xxx
  # CRON_ENABLE_APP_SYNC: true|false
  CALENDSO_ENCRYPTION_KEY: ${{ secrets.CI_CALENDSO_ENCRYPTION_KEY }}
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.CI_NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
  STRIPE_PRIVATE_KEY: ${{ secrets.CI_STRIPE_PRIVATE_KEY }}
  STRIPE_CLIENT_ID: ${{ secrets.CI_STRIPE_CLIENT_ID }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.CI_STRIPE_WEBHOOK_SECRET }}
  PAYMENT_FEE_PERCENTAGE: 0.005
  PAYMENT_FEE_FIXED: 10
  SAML_DATABASE_URL: postgresql://postgres:@localhost:5432/calendso
  SAML_ADMINS: pro@example.com
  NEXTAUTH_URL: http://localhost:3000
  NEXT_PUBLIC_IS_E2E: 1
  # EMAIL_FROM: e2e@cal.com
  # EMAIL_SERVER_HOST: ${{ secrets.CI_EMAIL_SERVER_HOST }}
  # EMAIL_SERVER_PORT: ${{ secrets.CI_EMAIL_SERVER_PORT }}
  # EMAIL_SERVER_USER: ${{ secrets.CI_EMAIL_SERVER_USER }}
  # EMAIL_SERVER_PASSWORD: ${{ secrets.CI_EMAIL_SERVER_PASSWORD }}
  # MS_GRAPH_CLIENT_ID: xxx
  # MS_GRAPH_CLIENT_SECRET: xxx
  # ZOOM_CLIENT_ID: xxx
  # ZOOM_CLIENT_SECRET: xxx
  SENDGRID_API_KEY: ${{ secrets.CI_SENDGRID_API_KEY }}
  SENDGRID_EMAIL: ${{ secrets.CI_SENDGRID_EMAIL }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  changes:
    name: Detect changes
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      pull-requests: read
    outputs:
      app-store: ${{ steps.filter.outputs.app-store }}
      embed: ${{ steps.filter.outputs.embed }}
      embed-react: ${{ steps.filter.outputs.embed-react }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app-store:
              - 'apps/web/**'
              - 'packages/app-store/**'
              - 'playwright.config.ts'
            embed:
              - 'apps/web/**'
              - 'packages/embeds/**'
              - 'playwright.config.ts'
            embed-react:
              - 'apps/web/**'
              - 'packages/embeds/**'
              - 'playwright.config.ts'

  type-check:
    name: Type check
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  test:
    name: Unit tests
    uses: ./.github/workflows/test.yml
    secrets: inherit

  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Production build
    uses: ./.github/workflows/production-build.yml
    secrets: inherit

  build-without-database:
    name: Production build (without database)
    uses: ./.github/workflows/production-build-without-database.yml
    secrets: inherit

  e2e:
    name: E2E tests
    needs: [changes, lint, build]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  e2e-app-store:
    name: E2E App Store tests
    if: ${{ needs.changes.outputs.app-store == 'true' }}
    needs: [changes, lint, build]
    uses: ./.github/workflows/e2e-app-store.yml
    secrets: inherit

  e2e-embed:
    name: E2E embeds tests
    if: ${{ needs.changes.outputs.embed == 'true' }}
    needs: [changes, lint, build]
    uses: ./.github/workflows/e2e-embed.yml
    secrets: inherit

  e2e-embed-react:
    name: E2E React embeds tests
    if: ${{ needs.changes.outputs.embed-react == 'true' }}
    needs: [changes, lint, build]
    uses: ./.github/workflows/e2e-embed-react.yml
    secrets: inherit

  analyze:
    needs: build
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
    secrets: inherit

  required:
    needs: [lint, type-check, test, build, e2e]
    if: always()
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
