name: Production Build (without database)

on:
  workflow_call:

jobs:
  env:
    name: Create env file
    uses: ./.github/workflows/env-create-file.yml
    secrets: inherit
  build:
    name: Build
    needs: env
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/cache-build
