name: Production Build

on:
  workflow_call:

jobs:
  env:
    name: Create env file
    uses: ./.github/workflows/env-create-file.yml
    secrets: inherit
  build:
    name: Build
    needs: env
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: calendso
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/cache-db
      - uses: ./.github/actions/cache-build
