name: Yarn Lock Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-check-lock:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Lint Code
        run: yarn lint
      
      - name: Check Yarn Lock
        run: |
          git diff --exit-code -- yarn.lock
        continue-on-error: true

