name: Yarn install

on:
  workflow_call:
    secrets:
      node_version:
        required: true

jobs:
  e2e-test:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules-yarn
          cache-fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}
      - run: yarn playwright install
      - name: Run tests
        run: yarn e2e
